package org.fishing.services;

public enum ObjectType {
  BUTTON_DUEL,
  BUTTON_CATCH,
  BUTTON_CATCH_FROM_MAIN,
  BUTTON_OK,
  BUTTON_GRAB,
  BUTTON_ROD_REEL,
  BUTTON_PICKUP,
  ICON_ROD_THREAD,
  ICON_ROD_THREAD_2,
  ICON_CLEAR_BAR,
  ICON_CLEAR_BAR_2,
  ICON_FIRST_PLACE,
  ICON_SECOND_PLACE,
  ICON_THIRD_PLACE,
  ICON_SECOND_ROUND,
  ICON_THIRD_ROUND,
  ICON_CHOOSE_CARD,
  ICON_DUEL_LOOSE,
  ICON_DUEL_WIN,
  ICON_DUEL_DRAW,
  ICON_SCORE_PANEL,
  BUTTON_BATTLE_LEAVE,
  RECEIVE_VIZOV_BUTTON
}
