package org.fishing;

public enum GameState {
  UNDEFINED,
  MAIN_MENU,
  FISH_BATTLE_1_START,
  FISH_BATTLE_1_RESULT,
  FISH_BATTLE_2_START,
  FISH_BATTLE_2_RESULT,
  FISH_BATTLE_3_START,
  FISH_BATTLE_3_RESULT,
  FISH_BATTLE_PRIZE_PLACE,
  FISH_BATTLE_LOOSE,
  FISH_BATTLE_PRIZES,
  STOP
}
